name: myenv
channels:
  - defaults
  - conda-forge
  - pytorch
dependencies:
  - python-telegram-bot
  - openai
  - httpx
  - tiktoken
  - python-dotenv
  - Pillow
  - numpy
  - aiohttp
  - pymysql
  - fastapi
  - uvicorn
  - pydub~=0.25.1
  - pytube~=15.0.0
  - gtts~=2.5.1
  - youtube-transcript-api=0.6.2
  - readability-lxml=0.8.1
  - lxml-html-clean=0.1.1
  - docling
  #- transformers
  - accelerate
  - faiss-gpu
  - langchain
  #- pytorch
  - pip
  - pip:
      - wolframalpha
      - duckduckgo_search
      #- torch
      - pyswisseph
      - openai-whisper
      - md2tgmd
      - clip
      - annoy
      - PyYAML
